### ISSUE TITLE
just stumbled across this

### ISSUE THREAD

**Issue by sirrodgepodge** [jazzyinstyle/morgan-body-ext#1]
am honored that my humble little fork of morgan has its own fork haha.

might be cool to add this functionality into morgan-body itself, what do you think?

**Comment by jazzyinstyle** [comment]
Hey Roger, nice to meet you. Sounds like a good idea.
I'll try to put the change in a pull request.. give me some time to work on it, due to other commitments..
Cheers!

**Comment by jazzyinstyle** [comment]
Hey Roger, please check on the Pull Request https://github.com/sirrodgepodge/morgan-body/pull/16 for the Feature update. Thanks.

**Comment by sirrodgepodge** [comment]
Nice to meet you as well and thank you so much, will follow up there :)
